### ISSUE TITLE
when hide or remove element, animatations  not work

### ISSUE THREAD

**Issue by ccjoe** [FormidableLabs/react-effects#15]
when the animate is run over, then the element will be back,
for example:
```
fadeOutDown: {
    animation: 'x 1s',
    animationName: Radium.keyframes(fadeOutDown, 'fadeOutDown'),
  }
```
when element is fadeOutDown, then is will be show  .

if add `display: 'none'`
animate not work

**Comment by juangallo** [comment]
Hi!
I'm with the exact same issue, were you able to resolve it?
If you were, can you tell me how?
Thanks!

**Comment by ccjoe** [comment]
@juangallo hi,  i made it by react-motion

**Comment by aweary** [comment]
You may need to set [`animation-fill-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode) so the styles are applied after the animation is finished!
