### ISSUE TITLE
Fade in -> Fade out Animation

### ISSUE THREAD

**Issue by alexgurr** [FormidableLabs/react-effects#16]
Hi.

Looking to animate a modal window with this. I've gotten fadeIn to work, but not sure how I can get it to fade out as well. I'm using Radium.

I've tried:

```
container: {
    display: 'block',

    hidden: {
      animationName: Radium.keyframes(fadeIn, 'fadeIn')
    },

    visible: {
      animationName: Radium.keyframes(fadeOut, 'fadeOut')
    }
}
```

And then in my class:

```
 <div
   role="dialog"
   style={[
   defaultStyles.container,
   rendered ? defaultStyles.container.visible : defaultStyles.container.hidden
   ]}
 >
```
But does the fadeIn, then the fadeOut, then fadesIn again. Any ideas?

**Comment by aweary** [comment]
I recommend referring to the [Radium](https://github.com/FormidableLabs/radium) repo for support resources to help with this. react-animations just exports object describing the animation and doesn't control how the animation is processed by the consuming style library. Thanks!
