### ISSUE TITLE
Animation Delay? 

### ISSUE THREAD

**Issue by ghost** [FormidableLabs/react-effects#18]
Any way to delay animations? 

```
import { slideInLeft } from 'react-animations';
import { StyleSheet, css } from 'aphrodite';

const styles = StyleSheet.create({
  slideInLeft: {
    animationDelay: '2s',
    animationName: slideInLeft,
    animationDuration: '3s'
  }
});
```

Adding the animation delay property did not work.

**Comment by aweary** [comment]
Hey @franciskim722, you should refer to the Aphrodite docs for support with this. react-animations just exports objects that describe the animation, and don't control how its processed by the consuming style library. Thanks!
