### ISSUE TITLE
How do i trigger an animation based on a click event ? 

### ISSUE THREAD

**Issue by vivekiyer114** [FormidableLabs/react-effects#21]
How to trigger an animation on a click event ? 
There is no documentation provided for it.

**Comment by aweary** [comment]
`react-animations` is a small set of animation descriptors and doesn't have any functionality regarding events. I would recommend referring to [the official React documentation on events](https://reactjs.org/docs/handling-events.html)

You can always use `setState` in an event handler to trigger a re-render with a new style (and animation) applied.
