### ISSUE TITLE
Export all animations as single object in default export

### ISSUE THREAD

**Issue by joshfarrant** [FormidableLabs/react-effects#23]
I believe it would be useful to define a default export in the main index file which exports an object containing all of the animations.

```js
export default {
  bounce,
  flash,
  pulse,
  // ...
};
```

Which can then be imported as

```js
import animations from 'react-animations';
```

The benefit of this is that you can allow a user/consumer to choose their own animations without having to import them all individually.

For example, I'm currently developing a Notification component that uses react-animations for it's entry and exit animations. I'd like to be able to expose a couple of props that let the consumer pick the animation that the Notification performs on entry and exit.

The simplest way to do this would be as follows.

```js
import animations from 'react-animations';

export const Notification = ({
  enterAnimationName,
  exitAnimationName,
}) => {
  const enterAnimation = animations[enterAnimationName];
  const exitAnimation = animations[exitAnimationName];
  
  // ...
};
```

Currently, this isn't possible as react-animations has no default export, so the value of `animations` is just `undefined`.

Generally speaking, I do think it's rare that someone would want to import all animations, and that it should be advised against if you are just planning on using a single animation. Saying that, I do think that there's utility in this feature.

More than happy to open a PR.

**Comment by joshfarrant** [comment]
Any thoughts on this? Would a PR from me help move this along?

**Comment by ryan-roemer** [comment]
Weird question -- can't someone just do:

```js
import * as animations from 'react-animations';
```

At least in the babel world transpiling, something like:

```js
// src/mod.js
export const foo = "foo";
export const bar = "bar";
export const num = 42;

// src/index.js
import * as mod from "./mod";

Object.keys(mod).forEach((key) => {
  console.log("TODO HERE", key, mod[key]);
});
```

when transpiled and run produces output like:

```
$ node lib/index.js 
TODO HERE foo foo
TODO HERE bar bar
TODO HERE num 42
```

/cc @mattcubitt

**Comment by mattcubitt** [comment]
Hi @joshfarrant yes you can use: 

` import * as animations from 'react-animations'; `

I think this would be a better solution than maintaining a list of animations on the default export.

**Comment by aweary** [comment]
I agree that `import *` is the right way to do this, since conceptually there isn't any default export for `react-animations`

**Comment by joshfarrant** [comment]
😑  ... Don't know why that hadn't occurred to me - cheers all! 👍
