### ISSUE TITLE
It seems to be really nice but too few documentation for newbies

### ISSUE THREAD

**Issue by ronnythedev** [FormidableLabs/react-effects#8]
Everything looks pretty nice with a lot of potential to simplify animations in React which is not easy for newbies like me.

After a couple of hours trying to use this project, I gave up. There is too few documentation for people not familiar with Radium, keyframes, etc.

**Comment by aweary** [comment]
Thanks for the feedback @ron-camaron! I'm happy to accept PRs for improvements to the documentation. It does assume you're familiar with Radium or another CSS-in-JS library, and it assumes you are familiar enough with CSS to know what keyframes are. I think those are definitely prerequisites for using `react-animations` successfully, but I'm happy to make things clearer where possible.

**Comment by smitch88** [comment]
I had similar issues with understanding `Radium` in general. @ron-camaron Its been awhile but if u want to revisit the lib with another css `lib` I ended up using `Aphrodite` instead and got an example up very quickly after that.

Here is a simple example for a splash screen w/ `React` + `Aphrodite` that Im using for an `Electron `app. It flashes some text and an image of the app on a 3s interval infinitely.

```
import React from 'react';
import { flash } from 'react-animations';
import { StyleSheet, css } from 'aphrodite/no-important';

const styles = StyleSheet.create({
  splash: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: '#111111'
  },
  splash__content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    animation: 'flash 3s infinite',
    animationName: flash
  },
  splash__image: {
    width: 60,
    height: 60
  },
  splash__text: {
    marginTop: 20,
    color: '#333333',
    fontSize: '1.2em',
    textTransform: 'uppercase'
  }
});

class SplashScreen extends React.Component {

  static propTypes = {
    image: React.PropTypes.string.isRequired,
    text: React.PropTypes.string.isRequired
  };

  render() {
    return (
      <div className={css(styles.splash)}>
        <div className={css(styles.splash__content)}>
          <img className={css(styles.splash__image)} src={this.props.image} />
          <p className={css(styles.splash__text)}>{this.props.text}</p>
        </div>
      </div>
    );
  }
}

export default SplashScreen;

```

**Comment by nitin42** [comment]
@ron-camaron @smitch88 You can also try [`animate-components`](https://github.com/nitin42/animate-components). I know its difficult to understand some docs (Radium or Aphrodite) but `react-animations` helped me a lot in doing animation stuff in React which further led me to develop my own library 😄

**Comment by just214** [comment]
I created an interactive demo for React-Animations that allows you to test out all of the available animations (and merge feature) on different text and icons. You can merge animations that you already merged and come up with some pretty interesting hybrids.  

You can find the live demo here: [http://rad.surge.sh](http://rad.surge.sh). 
The source code is [here](https://github.com/gojutin/react-animations-demo).

I will be happy to create a PR with a link to the demo in the README if the folks at FormidableLabs would like me to do so.

**Comment by AdamGerthel** [comment]
I've never used any CSS-in-JS library, and am not looking to start using one. Is it possible to use react-animations without it? If so, a basic example would be useful.

**Comment by aweary** [comment]
@AdamGerthel this library is just a collection of objects describing CSS animations which can be used with CSS-in-JS libraries. If you're looking for something similar with regular CSS I recommend https://daneden.github.io/animate.css/

**Comment by just214** [comment]
@AdamGerthel I know you said you don't want to learn another library, but for what it is worth, styled-components + react-animations is a great combo and very easy to get going with.

**Comment by AdamGerthel** [comment]
I ended up going with https://github.com/nitin42/animate-components but thanks for the clarification anyways!
