### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by kof** [FormidableLabs/react-effects#9]
Why is it react-animations, I don't see any dependency to react? It should be "cssinjs-animations" or similar.

**Comment by aweary** [comment]
The package name is mostly marketing, you're right that there's nothing specific to React. It might have a wider appeal if I rename it, but at this point I don't think I would want to put in the time to rename and republish it. Thanks for the issue though!

**Comment by kof** [comment]
Alright, published `cssinjs-animations` to npm, let me know if you want to use this namespace for it.
